short_name: full_example
namespace: local
version: 0.1.0
api_version: "0.1"
author: innoCampus <info@isis.tu-berlin.de>
name:
  de: Vollst√§ndiges Beispiel
  en: Full Example
languages: [de, en]
build_hooks:
  pre: npm run build
